-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT,
  email TEXT,
  profile_image_url TEXT,
  custom_status TEXT,
  custom_emoji TEXT,
  status TEXT DEFAULT 'offline' CHECK (status IN ('online', 'idle', 'dnd', 'invisible', 'offline')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Servers Table
CREATE TABLE IF NOT EXISTS servers (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  server_image_url TEXT,
  is_public BOOLEAN DEFAULT FALSE,
  owner_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  invite_code TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Channels Table
CREATE TABLE IF NOT EXISTS channels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_voice BOOLEAN DEFAULT FALSE,
  is_owner_only BOOLEAN DEFAULT FALSE,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Channel Messages Table
CREATE TABLE IF NOT EXISTS channel_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  sender_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  channel_id BIGINT REFERENCES channels(id) ON DELETE CASCADE,
  is_image BOOLEAN DEFAULT FALSE,
  file_url TEXT,
  file_name TEXT,
  file_type TEXT,
  file_size BIGINT,
  reply_to_id BIGINT REFERENCES channel_messages(id) ON DELETE SET NULL,
  edited_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Direct Messages (Chats) Table
CREATE TABLE IF NOT EXISTS chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  is_image BOOLEAN DEFAULT FALSE,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Friendships Table
CREATE TABLE IF NOT EXISTS friendships (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  requester_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  requested_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  status TEXT CHECK (status IN ('pending', 'accepted', 'declined')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(requester_id, requested_id)
);

-- 7. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT CHECK (type IN ('message', 'friend_request', 'call', 'server_invite')),
  title TEXT,
  message TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Server Roles Table
CREATE TABLE IF NOT EXISTS server_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  permissions BIGINT DEFAULT 0,
  position INTEGER DEFAULT 0,
  color INTEGER,
  hoist BOOLEAN DEFAULT FALSE,
  mentionable BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Server Invites Table
CREATE TABLE IF NOT EXISTS server_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  invite_code TEXT UNIQUE NOT NULL,
  created_by UUID REFERENCES profiles(id) ON DELETE CASCADE,
  max_uses INTEGER,
  uses INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Voice Channel Members Table
CREATE TABLE IF NOT EXISTS voice_channel_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id BIGINT REFERENCES channels(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  is_muted BOOLEAN DEFAULT FALSE,
  is_deafened BOOLEAN DEFAULT FALSE,
  is_video_enabled BOOLEAN DEFAULT FALSE,
  is_screen_sharing BOOLEAN DEFAULT FALSE,
  joined_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Server Users (Members) Table
CREATE TABLE IF NOT EXISTS server_users (
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (server_id, user_id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE servers ENABLE ROW LEVEL SECURITY;
ALTER TABLE channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE voice_channel_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_users ENABLE ROW LEVEL SECURITY;

-- Basic RLS Policies (Examples - need refinement based on exact requirements)

-- Profiles: Public read, self update
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Servers: Public servers viewable, members view private
CREATE POLICY "Servers viewable by everyone" ON servers FOR SELECT USING (is_public OR EXISTS (SELECT 1 FROM server_users WHERE server_id = servers.id AND user_id = auth.uid()));
CREATE POLICY "Users can create servers" ON servers FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- Channels: Viewable by server members
CREATE POLICY "Channels viewable by server members" ON channels FOR SELECT USING (EXISTS (SELECT 1 FROM server_users WHERE server_id = channels.server_id AND user_id = auth.uid()));

-- Channel Messages: Viewable by server members
CREATE POLICY "Messages viewable by server members" ON channel_messages FOR SELECT USING (EXISTS (SELECT 1 FROM server_users su JOIN channels c ON su.server_id = c.server_id WHERE c.id = channel_messages.channel_id AND su.user_id = auth.uid()));
CREATE POLICY "Members can insert messages" ON channel_messages FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Chats: Viewable by participants
CREATE POLICY "Chats viewable by participants" ON chats FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can insert chats" ON chats FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE channel_messages;
ALTER PUBLICATION supabase_realtime ADD TABLE chats;
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE voice_channel_members;
ALTER PUBLICATION supabase_realtime ADD TABLE friendships;

-- Trigger for new user profile creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, username)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'username');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
