-- ============================================
-- CREATE MISSING TABLE: server_user_roles
-- Run this in Supabase SQL Editor to fix role assignments
-- ============================================

CREATE TABLE IF NOT EXISTS server_user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  server_role_id BIGINT REFERENCES server_roles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, server_role_id)
);

-- Enable RLS
ALTER TABLE server_user_roles ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies

-- 1. View policies
CREATE POLICY "Anyone can view user roles" ON server_user_roles
  FOR SELECT USING (true);

-- 2. Manage policies (Insert/Update/Delete) for Server Owners
CREATE POLICY "Server owners can manage user roles" ON server_user_roles
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM server_roles
      JOIN servers ON servers.id = server_roles.server_id
      WHERE server_roles.id = server_user_roles.server_role_id
      AND servers.owner_id = auth.uid()
    )
  );

-- 3. Manage policies for users with MANAGE_ROLES permission
-- This is more complex, usually handled by checking if the acting user has a role with MANAGE_ROLES bit
-- For simplicity, we'll stick to server owners for now, or allow if they are admin

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_server_user_roles_user_id ON server_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_server_user_roles_role_id ON server_user_roles(server_role_id);

-- ============================================
-- DONE!
-- ============================================
