-- Roles Table
CREATE TABLE IF NOT EXISTS server_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#99aab5',
  position INTEGER NOT NULL, -- 0 is lowest (default role)
  permissions BIGINT DEFAULT 0,
  is_hoisted BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User Roles Junction
CREATE TABLE IF NOT EXISTS server_user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id BIGINT REFERENCES server_roles(id) ON DELETE CASCADE,
  UNIQUE(user_id, role_id)
);

-- Channel Overrides
CREATE TABLE IF NOT EXISTS channel_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id BIGINT REFERENCES channels(id) ON DELETE CASCADE,
  role_id BIGINT REFERENCES server_roles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  allow BIGINT DEFAULT 0,
  deny BIGINT DEFAULT 0,
  CHECK (role_id IS NOT NULL OR user_id IS NOT NULL)
);

-- Add is_private column to channels if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'channels' AND column_name = 'is_private') THEN
        ALTER TABLE channels ADD COLUMN is_private BOOLEAN DEFAULT false;
    END IF;
END $$;

-- RLS Policies

-- Enable RLS
ALTER TABLE server_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE server_user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_permissions ENABLE ROW LEVEL SECURITY;

-- Server Roles Policies
CREATE POLICY "Server members can view roles" ON server_roles
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_id FROM server_users WHERE server_id = server_roles.server_id
    )
  );

CREATE POLICY "Server admins can manage roles" ON server_roles
  FOR ALL USING (
    auth.uid() IN (
      SELECT owner_id FROM servers WHERE id = server_roles.server_id
    )
    -- TODO: Add check for MANAGE_ROLES permission when we have the function
  );

-- User Roles Policies
CREATE POLICY "Server members can view user roles" ON server_user_roles
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_id FROM server_users WHERE server_id = server_user_roles.server_id
    )
  );

CREATE POLICY "Server admins can manage user roles" ON server_user_roles
  FOR ALL USING (
    auth.uid() IN (
      SELECT owner_id FROM servers WHERE id = server_user_roles.server_id
    )
  );

-- Channel Permissions Policies
CREATE POLICY "Server members can view channel permissions" ON channel_permissions
  FOR SELECT USING (
    auth.uid() IN (
      SELECT user_id FROM server_users 
      WHERE server_id = (SELECT server_id FROM channels WHERE id = channel_permissions.channel_id)
    )
  );

CREATE POLICY "Server admins can manage channel permissions" ON channel_permissions
  FOR ALL USING (
    auth.uid() IN (
      SELECT owner_id FROM servers 
      WHERE id = (SELECT server_id FROM channels WHERE id = channel_permissions.channel_id)
    )
  );
