-- ============================================
-- CREATE DIRECT CALLS TABLE
-- Migration for Discord-style P2P calling system
-- ============================================

-- Table to track active direct calls between users
CREATE TABLE IF NOT EXISTS direct_calls (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  caller_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  callee_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT CHECK (status IN ('ringing', 'active', 'ended', 'rejected', 'missed')) NOT NULL DEFAULT 'ringing',
  call_type TEXT CHECK (call_type IN ('voice', 'video')) NOT NULL DEFAULT 'voice',
  started_at TIMESTAMPTZ DEFAULT NOW(),
  answered_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE direct_calls ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own calls" ON direct_calls
  FOR SELECT USING (auth.uid() = caller_id OR auth.uid() = callee_id);

CREATE POLICY "Users can create calls" ON direct_calls
  FOR INSERT WITH CHECK (auth.uid() = caller_id);

CREATE POLICY "Call participants can update call status" ON direct_calls
  FOR UPDATE USING (auth.uid() = caller_id OR auth.uid() = callee_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_direct_calls_caller ON direct_calls(caller_id);
CREATE INDEX IF NOT EXISTS idx_direct_calls_callee ON direct_calls(callee_id);
CREATE INDEX IF NOT EXISTS idx_direct_calls_status ON direct_calls(status);
CREATE INDEX IF NOT EXISTS idx_direct_calls_created_at ON direct_calls(created_at DESC);

-- Add to Realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE direct_calls;

-- ============================================
-- WEBRTC SIGNALS TABLE (if not exists)
-- ============================================

CREATE TABLE IF NOT EXISTS webrtc_signals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id UUID REFERENCES direct_calls(id) ON DELETE CASCADE,
  from_user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  to_user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  signal_type TEXT CHECK (signal_type IN ('offer', 'answer', 'ice-candidate')) NOT NULL,
  payload JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS on webrtc_signals
ALTER TABLE webrtc_signals ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can send WebRTC signals to specific users" ON webrtc_signals;
DROP POLICY IF EXISTS "Users can read their WebRTC signals" ON webrtc_signals;
DROP POLICY IF EXISTS "Users can delete their WebRTC signals" ON webrtc_signals;

-- RLS Policies for webrtc_signals
CREATE POLICY "Users can send WebRTC signals" ON webrtc_signals
  FOR INSERT WITH CHECK (auth.uid() = from_user_id);

CREATE POLICY "Users can read their WebRTC signals" ON webrtc_signals
  FOR SELECT USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

CREATE POLICY "Users can delete their WebRTC signals" ON webrtc_signals
  FOR DELETE USING (auth.uid() = from_user_id OR auth.uid() = to_user_id);

-- Indexes for webrtc_signals
CREATE INDEX IF NOT EXISTS idx_webrtc_signals_call_id ON webrtc_signals(call_id);
CREATE INDEX IF NOT EXISTS idx_webrtc_signals_from_user ON webrtc_signals(from_user_id);
CREATE INDEX IF NOT EXISTS idx_webrtc_signals_to_user ON webrtc_signals(to_user_id);

-- Add to Realtime publication
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE webrtc_signals;
EXCEPTION
  WHEN duplicate_object THEN
    NULL; -- Table already in publication
END $$;

-- ============================================
-- DONE!
-- ============================================
