-- Create server_user_roles table for role assignments
CREATE TABLE IF NOT EXISTS server_user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  server_role_id BIGINT REFERENCES server_roles(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, server_role_id)
);

-- Enable RLS
ALTER TABLE server_user_roles ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Server members can view role assignments" ON server_user_roles FOR SELECT USING (
  EXISTS (
    SELECT 1 FROM server_roles sr
    JOIN server_users su ON su.server_id = sr.server_id
    WHERE sr.id = server_user_roles.server_role_id
    AND su.user_id = auth.uid()
  )
);

CREATE POLICY "Users with manage roles can assign roles" ON server_user_roles FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM server_roles sr
    JOIN servers s ON s.id = sr.server_id
    WHERE sr.id = server_user_roles.server_role_id
    AND (
      s.owner_id = auth.uid()
      OR EXISTS (
        SELECT 1 FROM server_user_roles sur2
        JOIN server_roles sr2 ON sr2.id = sur2.server_role_id
        WHERE sur2.user_id = auth.uid()
        AND sr2.server_id = s.id
        AND (sr2.permissions & (1 << 5)) > 0  -- MANAGE_ROLES permission
      )
    )
  )
);

CREATE POLICY "Users with manage roles can remove roles" ON server_user_roles FOR DELETE USING (
  EXISTS (
    SELECT 1 FROM server_roles sr
    JOIN servers s ON s.id = sr.server_id
    WHERE sr.id = server_user_roles.server_role_id
    AND (
      s.owner_id = auth.uid()
      OR EXISTS (
        SELECT 1 FROM server_user_roles sur2
        JOIN server_roles sr2 ON sr2.id = sur2.server_role_id
        WHERE sur2.user_id = auth.uid()
        AND sr2.server_id = s.id
        AND (sr2.permissions & (1 << 5)) > 0  -- MANAGE_ROLES permission
      )
    )
  )
);

-- Add to Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE server_user_roles;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_server_user_roles_user_id ON server_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_server_user_roles_server_role_id ON server_user_roles(server_role_id);
