-- Create server_bans table
CREATE TABLE IF NOT EXISTS server_bans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id UUID REFERENCES servers(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  reason TEXT,
  banned_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(server_id, user_id)
);

-- RLS for server_bans
ALTER TABLE server_bans ENABLE ROW LEVEL SECURITY;

-- Only server members with BAN_MEMBERS permission or owner can view bans (simplified to members for now for UI consistency, or we can restrict it)
-- For now, let's allow any member to see the ban list if we want to show it in settings, otherwise restrict to admins.
-- Let's stick to: Owners and users with BAN_MEMBERS permission.
CREATE POLICY "Admins can view bans" ON server_bans
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM servers WHERE id = server_bans.server_id AND owner_id = auth.uid()
    )
    OR
    EXISTS (
      SELECT 1 FROM server_user_roles sur
      JOIN server_roles sr ON sur.role_id = sr.id
      WHERE sur.server_id = server_bans.server_id
      AND sur.user_id = auth.uid()
      AND (sr.permissions::bigint & 32) > 0
    )
  );

-- Function to kick a member
CREATE OR REPLACE FUNCTION kick_server_member(
  p_server_id UUID,
  p_user_id UUID
)
RETURNS VOID AS $$
DECLARE
  v_caller_id UUID;
  v_has_permission BOOLEAN;
  v_is_owner BOOLEAN;
BEGIN
  v_caller_id := auth.uid();

  -- Check if caller is owner
  SELECT (owner_id = v_caller_id) INTO v_is_owner
  FROM servers WHERE id = p_server_id;

  -- Check if caller has KICK_MEMBERS permission (bit 16 -> 1<<4)
  IF NOT v_is_owner THEN
    SELECT EXISTS (
      SELECT 1
      FROM server_user_roles sur
      JOIN server_roles sr ON sur.role_id = sr.id
      WHERE sur.server_id = p_server_id
      AND sur.user_id = v_caller_id
      AND (sr.permissions::bigint & 16) > 0 -- 16 is KICK_MEMBERS
    ) INTO v_has_permission;

    IF NOT v_has_permission THEN
      RAISE EXCEPTION 'Permission denied: You do not have permission to kick members.';
    END IF;
  END IF;

  -- Prevent kicking the owner
  IF EXISTS (SELECT 1 FROM servers WHERE id = p_server_id AND owner_id = p_user_id) THEN
    RAISE EXCEPTION 'Cannot kick the server owner.';
  END IF;

  -- Delete member
  DELETE FROM server_users
  WHERE server_id = p_server_id AND user_id = p_user_id;

  -- Delete all messages from this user in this server
  DELETE FROM channel_messages
  WHERE sender_id = p_user_id
  AND channel_id IN (
    SELECT id FROM channels WHERE server_id = p_server_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to ban a member
CREATE OR REPLACE FUNCTION ban_server_member(
  p_server_id UUID,
  p_user_id UUID,
  p_reason TEXT
)
RETURNS VOID AS $$
DECLARE
  v_caller_id UUID;
  v_has_permission BOOLEAN;
  v_is_owner BOOLEAN;
BEGIN
  v_caller_id := auth.uid();

  -- Check if caller is owner
  SELECT (owner_id = v_caller_id) INTO v_is_owner
  FROM servers WHERE id = p_server_id;

  -- Check if caller has BAN_MEMBERS permission (bit 32 -> 1<<5)
  IF NOT v_is_owner THEN
    SELECT EXISTS (
      SELECT 1
      FROM server_user_roles sur
      JOIN server_roles sr ON sur.role_id = sr.id
      WHERE sur.server_id = p_server_id
      AND sur.user_id = v_caller_id
      AND (sr.permissions::bigint & 32) > 0 -- 32 is BAN_MEMBERS
    ) INTO v_has_permission;

    IF NOT v_has_permission THEN
      RAISE EXCEPTION 'Permission denied: You do not have permission to ban members.';
    END IF;
  END IF;

  -- Prevent banning the owner
  IF EXISTS (SELECT 1 FROM servers WHERE id = p_server_id AND owner_id = p_user_id) THEN
    RAISE EXCEPTION 'Cannot ban the server owner.';
  END IF;

  -- Insert into bans
  INSERT INTO server_bans (server_id, user_id, reason, banned_by)
  VALUES (p_server_id, p_user_id, p_reason, v_caller_id)
  ON CONFLICT (server_id, user_id) DO UPDATE
  SET reason = p_reason, banned_by = v_caller_id;

  -- Delete member
  DELETE FROM server_users
  WHERE server_id = p_server_id AND user_id = p_user_id;

  -- Delete all messages
  DELETE FROM channel_messages
  WHERE sender_id = p_user_id
  AND channel_id IN (
    SELECT id FROM channels WHERE server_id = p_server_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update server_users INSERT policy to prevent banned users from joining
DROP POLICY IF EXISTS "Users can join servers" ON server_users;
CREATE POLICY "Users can join servers" ON server_users 
FOR INSERT WITH CHECK (
  auth.uid() = user_id 
  AND NOT EXISTS (
    SELECT 1 FROM server_bans 
    WHERE server_id = server_users.server_id 
    AND user_id = auth.uid()
  )
);
